# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6298de501fe19e17c83d2e430213f9e8d5c02f462678747306455e526b06a8baaa4f788726fa86c8ffd252848447138eb1834aa5c2bf4bad285e97538bccc59

test:
  secret_key_base: 3a3d869df2e561926a1d51993acb97a5d8d4e913d4b00235575441579124a9f2b571a7572b732ec53e23221392a47c8636ddf9be1611ab25eab1aece87a2d1e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
