# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' ) { name: 'Copenhagen' ))
#   Mayor.create(name: 'Emanuel', city: cities.first)


Blogger.create(name: 'Aaron Hayman',       twitter: 'aaronhayman',    websiteurl:'http://www.functionalgibberish.com/ ',      websitename:'functionalgibberish.com', rss:'http://www.functionalgibberish.com/blog?format=rss')
Blogger.create(name: 'Adam Byram',       twitter: 'adambyram',    websiteurl:'http://www.adambyram.com/',      websitename:'adambyram.com', rss:'http://www.adambyram.com/feed/')
Blogger.create(name: 'Adam Caudill',       twitter: 'adamcaudill',    websiteurl:'https://adamcaudill.com/',      websitename:'adamcaudill.com', rss:'https://adamcaudill.com/atom.xml')
Blogger.create(name: 'Adrian Carr',      twitter: '',           websiteurl:'http://adriancarr.com/',        websitename:'adriancarr.com', rss:'http://adriancarr.com/feed/')
Blogger.create(name: 'Al Zaudtke',      twitter: 'AlZaudtke',    websiteurl:'http://zaudtke.com/',      websitename:'zaudtke.com')
Blogger.create(name: 'Alan Stevens',    twitter: 'alanstevens',    websiteurl:'http://halanstevens.com/',      websitename:'halanstevens.com', rss:'http://halanstevens.com/blog/feed/')
Blogger.create(name: 'Alex Klibisz',       twitter: 'alexklibisz',    websiteurl:'http://alexklibisz.github.io/',     websitename:'alexklibisz.github.io', rss:'http://alexklibisz.github.io/feed.xml')
Blogger.create(name: 'Avdi Grimm',       twitter: 'avdi',         websiteurl:'http://about.avdi.org/',        websitename:'avdi.org', rss:'http://devblog.avdi.org/feed/')
Blogger.create(name: 'Bill Morefield',       twitter: 'bmorefield ',         websiteurl:'http://www.billmorefield.com/',        websitename:'billmorefield.com', rss:'http://feedpress.me/bmorefield')
Blogger.create(name: 'Bob Muenchen',       twitter: 'BobMuenchen',         websiteurl:'http://r4stats.com/',        websitename:'r4stats.com', rss:'http://r4stats.com/feed/')
Blogger.create(name: 'Bob Yexley',       twitter: 'ryexley',         websiteurl:'http://bob.yexley.net/',        websitename:'bob.yexley.net', rss:'http://bob.yexley.net/rss/')
Blogger.create(name: 'Brandon Ballentine',     twitter: '', websiteurl:'http://www.brandonballentine.com/', websitename:'brandonballentine.com', rss:'')
Blogger.create(name: 'Brice Wilson',       twitter: 'brice_wilson',         websiteurl:'https://www.bricewilson.net/',        websitename:'www.bricewilson.net', rss:'https://www.bricewilson.net/rss/')
Blogger.create(name: 'Bryan Headrick',       twitter: 'BryanHeadrick',    websiteurl:'http://bryanheadrick.com/',      websitename:'bryanheadrick.com', rss:'')
Blogger.create(name: 'Cameron Presley',   twitter: 'PhilipCPresley',   websiteurl:'http://thesoftwarementor.com/',     websitename:'thesoftwarementor.com', rss:'http://blog.thesoftwarementor.com/feed/')
Blogger.create(name: 'Chris Brakebill',     twitter: 'braker1nine',   websiteurl:'http://chrisbrakebill.com/',      websitename:'chrisbrakebill.com', rss:'http://chrisbrakebill.com/atom.xml')
Blogger.create(name: 'ChristinaHarlow',       twitter: 'cm_harlow',    websiteurl:'http://christinaharlow.com/',      websitename:'christinaharlow.com', rss:'http://christinaharlow.com/atom.xml')
Blogger.create(name: 'Christopher Lamm',     twitter: 'the_anti_chris',   websiteurl:'http://theantichris.com/',      websitename:'theantichris.com', rss:'http://theantichris.com/feed/')
Blogger.create(name: 'Chris Keathley',       twitter: 'ChrisKeathley',    websiteurl:'http://keathley.io/',         websitename:'keathley.io', rss:'http://keathley.io/feed.xml')
Blogger.create(name: 'Colin Mollenhour',     twitter: 'colinmollenhour',  websiteurl:'http://colin.mollenhour.com/',    websitename:'colin.mollenhour.com', rss:'http://colin.mollenhour.com/feed/')
Blogger.create(name: 'Dave Moore',     twitter: 'davemoore_io',  websiteurl:'http://davemoore.io',    websitename:'davemoore.io/category', rss:'http://davemoore.io/feed/')
Blogger.create(name: 'David Angel',     twitter: 'Davidius',  websiteurl:'http://davidangel.net/',    websitename:'davidangel.net', rss:'http://davidangel.net/blog/feed/')
Blogger.create(name: 'Devon Campbell',       twitter: 'raddevon',       websiteurl:'http://raddevon.com',         websitename:'raddevon.com', rss:'http://raddevon.com/articles/feed')
Blogger.create(name: 'Doc Isaac',   twitter: 'johannhat',websiteurl:'http://superdocisaac.tumblr.com/',websitename:'superdocisaac.tumblr.com', rss:'http://superdocisaac.tumblr.com/rss')
Blogger.create(name: 'Dylan Wolf', twitter: 'dylanwolf', websiteurl:'http://www.dylanwolf.com/', websitename:'dylanwolf.com', rss:'http://www.dylanwolf.com/feed/')
Blogger.create(name: 'Emily Schleiner',       twitter: 'cordial_emily',    websiteurl:'https://knownhabits.wordpress.com/ ',      websitename:'knownhabits.wordpress.com', rss:'https://knownhabits.wordpress.com/feed/')
Blogger.create(name: 'Gavin Wiggins',  twitter: 'wigging', websiteurl:'http://tinkker.io', websitename:'tinkker.io', rss:'feed://tinkker.io/feed.xml')
Blogger.create(name: 'Geoff Mazeroff',    twitter: 'geoffmazeroff',    websiteurl:'http://geoffmazeroff.com/',       websitename:'geoffmazeroff.com',rss:'http://www.geoffmazeroff.com/feed/')
Blogger.create(name: 'Jakob Myers',        twitter: 'iamjakob23',     websiteurl:'http://iamjakob.com/',        websitename:'iamjakob.com')
Blogger.create(name: 'James Kolpack',       twitter: 'poprhythm',       websiteurl:'http://popcyclical.com/',    websitename:'popcyclical.com', rss:'http://feeds.feedburner.com/popcyclical')
Blogger.create(name: 'James Nakamura',       twitter: 'nakadude',       websiteurl:'http://nakadude.blogspot.com',    websitename:'nakadude.blogspot.com', rss:'http://nakadude.blogspot.com/feeds/posts/default')
Blogger.create(name: 'Jamie Phillips',       twitter: 'phillipsj73',       websiteurl:'http://www.phillipsj.net/blog/html/index.html',    websitename:'phillipsj.net', rss:'http://www.phillipsj.net/blog/html/rss.html')
Blogger.create(name: 'Jared Smith',     twitter: 'jaredthecoder', websiteurl:'https://jaredmichaelsmith.com', websitename:'jaredmichaelsmith.com', rss:'https://jaredmichaelsmith.com/rss/')
Blogger.create(name: 'Jeff Thurston',       twitter: 'jeffyt',    websiteurl:'http://www.jeffthurston.com/',      websitename:'jeffthurston.com', rss:'http://www.jeffthurston.com/feed/')
Blogger.create(name: 'Jeremy Fairbank',      twitter: 'elpapapollo',    websiteurl:'http://blog.jeremyfairbank.com',    websitename:'blog.jeremyfairbank.com', rss:'http://blog.jeremyfairbank.com/feed')
Blogger.create(name: 'Jonathan Kemp',       twitter: 'jonkemp',      websiteurl:'http://jonkemp.com/',       websitename:'jonkemp.com', rss:'http://jonkemp.com/feed')
Blogger.create(name: 'Joseph Agreda',     twitter: 'jagreda', websiteurl:'http://probabilitytree.com/', websitename:'probabilitytree.com', rss:'')    
Blogger.create(name: 'Josh Carroll',       twitter: 'jwcarroll',      websiteurl:'http://technofattie.com',       websitename:'technofattie.com', rss:'http://www.technofattie.com/rss.xml')
Blogger.create(name: 'Joshua Miller', twitter: '_jshmllr', websiteurl:'https://medium.com/@_jshmllr/', websitename:'medium.com/@jshmllr', rss:'http://medium.com/feed/@jshmllr')
Blogger.create(name: 'Levi Smith',       twitter: 'GaTechGrad',      websiteurl:'http://levidsmith.com/',       websitename:'levidsmith.com', rss:'http://levidsmith.com/feed')
Blogger.create(name: 'Michael C. Neel',       twitter: 'ViNull',      websiteurl:'http://www.vinull.com/',       websitename:'vinull.com', rss:'http://www.vinull.com/feed/')
Blogger.create(name: 'Michael Wender',       twitter: 'mwender',    websiteurl:'http://mwender.com/',      websitename:'mwender.com', rss:'http://feed.mwender.com/')
Blogger.create(name: 'Neville Scheevel',   twitter: '_Neville',websiteurl:'http://scheevel.blogspot.com/',websitename:'scheevel.blogspot.com', rss:'http://scheevel.blogspot.com/feeds/posts/default')
Blogger.create(name: 'Nick Bradbury',     twitter: 'nbradbury', websiteurl:'http://nickbradbury.com/', websitename:'nickbradbury.com', rss:'http://nickbradbury.com/feed/')
Blogger.create(name: 'Phillip Andreason',      twitter: 'InfraredBaboon',   websiteurl:'https://codeukemi.wordpress.com/',  websitename:'codeukemi.wordpress.com', rss:'https://codeukemi.wordpress.com/feed/')
Blogger.create(name: 'Preston Garland',   twitter: 'wpgarland',websiteurl:'http://prestongarland.com/',websitename:'prestongarland.com', rss:'')
Blogger.create(name: 'Reid Evans',      twitter: 'ReidNEvans',     websiteurl:'http://reidev275.azurewebsites.net/', websitename:'reidev275.azurewebsites.net', rss:'http://reidev275.azurewebsites.net/rss/')
Blogger.create(name: 'Rob Gillen',        twitter: 'argodev',     websiteurl:'http://www.gillenfamily.net/', websitename:'gillenfamily.net', rss:'http://www.gillenfamily.net/blog?format=rss')
Blogger.create(name: 'Ronnie Goodrich',       twitter: 'kahootbird',    websiteurl:'http://www.kahootbird.com/',      websitename:'kahootbird.com', rss:'http://www.kahootbird.com/?feed=rss2')
Blogger.create(name: 'SDE Science Lover',     twitter: 'sdesciencelover', websiteurl:'http://sdesciencelover.typepad.com/', websitename:'sdesciencelover.typepad.com', rss:'http://sdesciencelover.typepad.com/blog/atom.xml')    
Blogger.create(name: 'Stephen Long', twitter: 'long2know', websiteurl:'https://long2know.com/', websitename:'long2know.com', rss:'')
Blogger.create(name: 'Steve Barbour',        twitter: 'steverb',       websiteurl:'http://www.steverb.com/',       websitename:'steverb.com', rss:'http://www.steverb.com/syndication.axd')
Blogger.create(name: 'Thilina Gunarathne',        twitter: 'thilina',       websiteurl:'http://thilina.gunarathne.org/',       websitename:'thilina.gunarathne.org')
Blogger.create(name: 'Thomas Daugherty',       twitter: 'Z33Studios',    websiteurl:'http://thomasdaugherty.com',      websitename:'thomasdaugherty.com', rss:'http://thomasdaugherty.com/blog/feed/')
Blogger.create(name: 'Travis Graham',        twitter: 'grahamt1',       websiteurl:'http://blog.tgraham.us/',       websitename:'blog.tgraham.us', rss:'http://blog.tgraham.us/rss')
Blogger.create(name: 'Tyler Jennings',       twitter: 'JenningsTCJ',    websiteurl:'http://tylerscode.com/',        websitename:'tylerscode.com', rss:'http://tylerscode.com/feed/')
Blogger.create(name: 'Wade Chandler',       twitter: 'wadechandler',    websiteurl:'http://wadechandler.blogspot.com/',      websitename:'wadechandler.blogspot.com', rss:'http://wadechandler.blogspot.com/feeds/posts/default')
Blogger.create(name: 'Wally McClure', twitter: 'wbm', websiteurl:'http://scalabledevelopment.com/', websitename:'scalabledevelopment.com', rss:'')
Blogger.create(name: 'William McKeehan',       twitter: 'mckeehan',    websiteurl:'http://www.mckeehan.info/',        websitename:'mckeehan.info')
Blogger.create(name: 'W. Anthony Ellison',     twitter: 'tnwae', websiteurl:'http://rt38.net/', websitename:'rt38.net', rss:'')
    